### PR TITLE
Add styles to Blogs entries and general

### PR DESCRIPTION
**Pull request by yanmarex**

### CODE REVIEW

**Comment by DiptoChakrabarty** [comment]
hey @yanmarex  the designs look good , but for each post I am unable to click the read more button and check the posts , can you please check this

**Comment by yanmarex** [comment]
Hi @DiptoChakrabarty . Try to remove and install node_modules. I run the project locally. Are you using Docker?

**Comment by DiptoChakrabarty** [comment]
No I am running locally only ,I am just not getting the read more button  and check the individual posts by users

**Comment by yanmarex** [comment]
Can you provide some screenshots of the problem? and what browser you are using.

**Comment by DiptoChakrabarty** [comment]
Sure , it is coming like this 
image

**Comment by yanmarex** [comment]
Well. I going to work on that now.

**Comment by DiptoChakrabarty** [comment]
Okay cool , If it is okay Ill can merge these commits in the development branch , and once this issue is fixed I will merge it to the master branch

**Comment by yanmarex** [comment]
Bug fixed! The Boss will be happy with this PR.

**Comment by DiptoChakrabarty** [comment]
Thank you , now  I am able to see the button  and the site looks really cool :)

**Pull request merged**
